---

- name: import Datastax repo key
  rpm_key:
    state: present
    key: http://rpm.datastax.com/rpm/repo_key

- name: Add Datastax community repository
  yum_repository:
    name: "datastax-dsc"
    description: "DataStax Repo for Apache Cassandra"
    baseurl: "http://rpm.datastax.com/community"
    enabled: yes
