---

- name: Cassandra | Add the datastax repository apt-key
  apt_key:
    url: "http://debian.datastax.com/debian/repo_key"
    state: present

- name: Cassandra | Add the datastax repository
  apt_repository:
    repo: "deb http://debian.datastax.com/community {{ datastax_dsc_major }}.{{ datastax_dsc_minor }} main"
    state: present

- name: prevent daemons from starting after installing a package
  copy:
    dest: /usr/sbin/policy-rc.d
    mode: '0755'
    content: "#!/bin/sh\nexit 101\n"
