---
dependency:
  name: galaxy
  requirements_file: requirements.yml
  options:
    ignore-certs: True

driver:
  name: docker
docker:
  containers:
    # - name: centos-6-cassandra-2.2.6
    #   image: centos
    #   image_version: 6.8
    #   cap_add: SYS_RESOURCE

    - name: centos-6-cassandra-2.2.8
      image: centos
      image_version: 6.8
      cap_add: SYS_RESOURCE

    # - name: ubuntu-14-04-2.2.6
    #   image: ubuntu
    #   image_version: 14.04
    #   cap_add: SYS_RESOURCE

    - name: ubuntu-14-04-2.2.8
      image: ubuntu
      image_version: 14.04
      cap_add: SYS_RESOURCE

ansible:
  playbook: playbook.yml

  host_vars:
    # centos-6-cassandra-2.2.6:
    #   datastax_dsc_patch: 6
    centos-6-cassandra-2.2.8:
      datastax_dsc_patch: 8
    # ubuntu-14-04-2.2.6:
    #   datastax_dsc_patch: 6
    ubuntu-14-04-2.2.8:
      datastax_dsc_patch: 8

verifier:
  name: testinfra
